apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pods
spec:
  replicas: 9
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:     
      labels:
        app: my-pod
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: ubuntu
          image: ghcr.io/takara9/ex1:1.0
          volumeMounts:
          - name: work-vol
            mountPath: /mnt
      topologySpreadConstraints: # トポロジー・スプレッド・コンストレインツ
        - topologyKey: kubernetes.io/hostname  # ノードの分散配置
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: my-pod
        - topologyKey: topology.kubernetes.io/zone  # ゾーンに分散配置
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: my-pod
      volumes:
        - name: work-vol
          emptyDir:
            sizeLimit: 50Mi 
  